<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZx2jbve\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZx2jbve/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZx2jbve.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZx2jbve\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZx2jbve\appProdProjectContainer([
    'container.build_hash' => 'Zx2jbve',
    'container.build_id' => '18f5162a',
    'container.build_time' => 1592216259,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZx2jbve');
